package envcontract

// Fail-fast без мягкой депрекации: без него апгрейд с непровённым .env тихо
// подменял бы значение оператора дефолтом вместо отказа старта.
var Renamed = map[string]string{
	"GOTCHA_METRIC_EVAL_INTERVAL":     "GOTCHA_METRIC_EVAL_INTERVAL_SECONDS",
	"GOTCHA_PROFILE_EVAL_INTERVAL":    "GOTCHA_PROFILE_EVAL_INTERVAL_SECONDS",
	"GOTCHA_HOST_EVAL_INTERVAL":       "GOTCHA_HOST_EVAL_INTERVAL_SECONDS",
	"GOTCHA_SLO_EVAL_INTERVAL":        "GOTCHA_SLO_EVAL_INTERVAL_SECONDS",
	"GOTCHA_ESCALATION_INTERVAL":      "GOTCHA_ESCALATION_INTERVAL_SECONDS",
	"GOTCHA_RETENTION_DAYS":           "GOTCHA_EVENT_RETENTION_DAYS",
	"GOTCHA_SERVER_URL":               "GOTCHA_PROBE_SERVER_URL",
	"GOTCHA_INGEST_RATE_LIMIT":        "GOTCHA_INGEST_RATE_PER_SEC",
	"GOTCHA_AGENT_DIST_DIR":           "GOTCHA_DIST_DIR",
	"GOTCHA_AGENT_DIST_RATE_PER_MIN":  "GOTCHA_DIST_RATE_PER_MIN",
	"GOTCHA_ADDR":                     "GOTCHA_LISTEN_ADDR",
	"GOTCHA_LOG_LEVEL":                "GOTCHA_LOGGING_LEVEL",
	"GOTCHA_LOG_FORMAT":               "GOTCHA_LOGGING_FORMAT",
	"GOTCHA_LOCAL_REGION":             "GOTCHA_UPTIME_LOCAL_REGION",
	"GOTCHA_REGISTRATION":             "GOTCHA_REGISTRATION_MODE",
	"GOTCHA_EXPORT_TTL_HOURS":         "GOTCHA_EXPORT_RETENTION_HOURS",
	"GOTCHA_SCRUB_KEYS":               "GOTCHA_SCRUB_DENY_KEYS",
	"GOTCHA_SCRUB_ALLOW_KEYS":         "GOTCHA_SCRUB_KEEP_KEYS",
	"GOTCHA_RUN_EVALUATORS":           "GOTCHA_EVALUATORS_ENABLED",
	"GOTCHA_AUTO_MIGRATE":             "GOTCHA_AUTO_MIGRATE_ENABLED",
	"GOTCHA_ALLOW_INSECURE_SECRET":    "GOTCHA_SECRET_KEY_ALLOW_INSECURE",
	"GOTCHA_MAX_BUFFER_BYTES":         "GOTCHA_MAX_WRITER_BUFFER_BYTES",
	"GOTCHA_MAX_QUEUE_BYTES":          "GOTCHA_MAX_INGEST_QUEUE_BYTES",
	"GOTCHA_PROBE_TOKEN":              "GOTCHA_PROBE_KEY",
	"GOTCHA_EXTERNAL_CHANNEL_DETAILS": "GOTCHA_EXTERNAL_CHANNEL_DETAILS_ENABLED",
	"GOTCHA_OIDC_NAME":                "GOTCHA_OIDC_DISPLAY_NAME",
	"GOTCHA_PURGE_RECONCILE_HOURS":    "GOTCHA_PROJECT_PURGE_RECONCILE_HOURS",
	"GOTCHA_AGENT_INTERVAL":           "GOTCHA_AGENT_INTERVAL_SECONDS",
	"GOTCHA_AGENT_KEY":                "GOTCHA_AGENT_INGEST_KEY",
	"GOTCHA_AGENT_TLS_SKIP_VERIFY":    "GOTCHA_AGENT_TLS_INSECURE_SKIP_VERIFY",
	// Общий неймспейс GOTCHA_* без префикса означал, что заданная напрямую
	// GOTCHA_PG_PASSWORD не давала ни эффекта, ни диагностики — её читает только Compose.
	"GOTCHA_PG_PASSWORD":  "GOTCHA_COMPOSE_PG_PASSWORD",
	"GOTCHA_CH_PASSWORD":  "GOTCHA_COMPOSE_CH_PASSWORD",
	"GOTCHA_PG_MEM_LIMIT": "GOTCHA_COMPOSE_PG_MEM_LIMIT",
	"GOTCHA_CH_MEM_LIMIT": "GOTCHA_COMPOSE_CH_MEM_LIMIT",
	"GOTCHA_MEM_LIMIT":    "GOTCHA_COMPOSE_MEM_LIMIT",
	"GOTCHA_NET_MTU":      "GOTCHA_COMPOSE_NET_MTU",
	"GOTCHA_PORT":         "GOTCHA_COMPOSE_PORT",
	"GOTCHA_BIND":         "GOTCHA_COMPOSE_BIND",
	"GOTCHA_VERSION":      "GOTCHA_BUILD_VERSION",
	"GOTCHA_COMMIT":       "GOTCHA_BUILD_COMMIT",
	"GOTCHA_DATE":         "GOTCHA_BUILD_DATE",
}

var AgentOwned = []string{
	"GOTCHA_AGENT_INTERVAL",
	"GOTCHA_AGENT_KEY",
	"GOTCHA_AGENT_TLS_SKIP_VERIFY",
}

// Новое имя не является (и не может стать) полем ни cmd/gotcha.Config,
// ни internal/agent.Config — только Docker Compose/Makefile.
var InfraOwned = []string{
	"GOTCHA_PG_PASSWORD",
	"GOTCHA_CH_PASSWORD",
	"GOTCHA_PG_MEM_LIMIT",
	"GOTCHA_CH_MEM_LIMIT",
	"GOTCHA_MEM_LIMIT",
	"GOTCHA_NET_MTU",
	"GOTCHA_PORT",
	"GOTCHA_BIND",
	"GOTCHA_VERSION",
	"GOTCHA_COMMIT",
	"GOTCHA_DATE",
}
