-- backward-compatible: yes (UPDATE только текстового столбца, схема не меняется)
-- A1 (аудит security P1-1/ops P0/security P2-1): last_error нёс сырые
-- секреты доставки. До этого релиза email.go оборачивал ошибку RCPT через
-- %w — сервер обычно эхает адрес получателя в тексте ответа ("550 <addr>:
-- rejected"); webhook.go вставлял non-2xx тело ответа как есть — сломанный
-- получатель мог отразить в нём URL цели с токеном в пути/query. Обе течи
-- зачинены у источника (email.go/webhook.go, тот же коммит), но уже
-- накопленные до апгрейда строки notification_outbox несут эти секреты —
-- ретеншн очереди 7 дней (janitor), но в день апгрейда они ещё видны
-- оператору на странице /alerts/deliveries. Разово нейтрализуем то, что уже
-- утекло в last_error; новые записи после апгрейда приходят уже чистыми.
UPDATE notification_outbox SET last_error = '[redacted on upgrade]' WHERE last_error <> '';
